#
# Copyright 2016-2017 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Template
metadata:
  name: hawkular-services
  annotations:
    openshift.io/display-name: Hawkular Services
    description: Hawkular Services all-in-one (including Hawkular Alerts and Hawkular Inventory).
    iconClass: icon-wildfly
    tags: hawkular,hawkular-services,alerts,manageiq

parameters:
- name: HAWKULAR_SERVICES_IMAGE
  description: What docker image should be used for Hawkular Services.
  displayName: Hawkular Services Docker Image
  value: hawkular/hawkular-services:0.38.0.Final
- name: HAWKULAR_SERVICES_DATA_LIMIT
  description: Maximum amount data used by Hawkular Services container (mostly logging).
  displayName: Hawkular Services Container Data Limit
  value: 1Gi
- name: ROUTE_NAME
  description: Public route with this name will be created.
  displayName: Route Name
  value: hawkular-services
- name: ROUTE_HOSTNAME
  description: Under this hostname the Hawkular Services will be accessible, if left blank a value will be defaulted.
  displayName: Hostname
- name: HAWKULAR_USE_SSL
  description: Should the self-signed certificate be created
  displayName: Use SSL
  value: "true"
- name: HAWKULAR_USER
  description: Username that is used for accessing the Hawkular Services, if left blank a value will be generated.
  displayName: Hawkular Services User
  from: '[a-zA-Z0-9]{16}'
  generate: expression
- name: HAWKULAR_PASSWORD
  description: Password that is used for accessing the Hawkular Services, if left blank a value will be generated.
  displayName: Hawkular Services Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
labels:
  template: hawkular-services
message: Credentials for Hawkular Services are ${HAWKULAR_USER}:${HAWKULAR_PASSWORD}

objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[{"namespace":"","kind":"Service"}]'
    name: hawkular-services
  spec:
    ports:
    - name: http-8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https-8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: admin-9990-tcp
      port: 9990
      protocol: TCP
      targetPort: 9990
    - name: metrics-9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779
    selector:
      name: hawkular-services
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: ${ROUTE_NAME}
  spec:
    host: ${ROUTE_HOSTNAME}
    to:
      kind: Service
      name: hawkular-services
    port:
      targetPort: http-8080-tcp

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: hawkular-services
  spec:
    replicas: 1
    selector:
      name: hawkular-services
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: hawkular-services
      spec:
        containers:
        - image: ${HAWKULAR_SERVICES_IMAGE}
          env:
          - name: HAWKULAR_USE_SSL
            value: ${HAWKULAR_USE_SSL}
          - name: HAWKULAR_USER
            value: ${HAWKULAR_USER}
          - name: HAWKULAR_PASSWORD
            value: ${HAWKULAR_PASSWORD}
          name: hawkular-services
          volumeMounts:
          - name: h-services-data
            mountPath: /var/opt/hawkular
          ports:
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 9990
          - containerPort: 9779
          livenessProbe:
            exec:
              command:
              - /opt/hawkular/bin/ready.sh
            initialDelaySeconds: 180
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
              - /opt/hawkular/bin/ready.sh
            initialDelaySeconds: 35
            timeoutSeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 12
          resources:
            requests:
              memory: 1024Mi
              cpu: 2000m
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: h-services-data
          persistentVolumeClaim:
            claimName: h-services-pvc

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: h-services-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${HAWKULAR_SERVICES_DATA_LIMIT}
